// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_content_delivery_bucket": "encountertracker-20180912125712--hostingbucket",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "http://encountertracker-20180912125712--hostingbucket.s3-website-ap-southeast-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "ap-southeast-2:9dd15ccb-d5d0-4634-a177-6195416a761e",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_CaIJfM3rd",
    "aws_user_pools_web_client_id": "74m74te6dr0ppmdagshjkjqhmg"
};


export default awsmobile;
